services:
  - type: web
    name: free-server
    env: python
    runtime: python-3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
